import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nextjs Prisma Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className={styles.home}>
          <Link href='/user'>
         { <button>Click To Enter User Job Profile Information</button> }
         </Link>
        </section>
      </main>
    </div>
  )
}

export default Home
